### ISSUE TITLE
Cannot validate certificate for xx.xxx.xxx.xx because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by parkr** [rakyll/boom#56] opened 2014-12-30 20:14 UTC
Very interesting x509 problem:

```text
~$ boom -n 1000 -c 100 https://google.com
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Error distribution:
  [1000]	Get https://74.125.226.38: x509: cannot validate certificate for 74.125.226.38 because it doesn't contain any IP SANs
~$ boom -n 1000 -c 100 http://google.com
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Summary:
  Total:	6.6467 secs.
  Slowest:	1.9418 secs.
  Fastest:	0.2918 secs.
  Average:	0.6369 secs.
  Requests/sec:	150.4510

Status code distribution:
  [200]	1000 responses

Response time histogram:
  [...]
```

I get the same failure for every HTTPS address I try out. Have you seen this before? I spent half an hour or so googling around to no avail.

**Comment by ssskip** [comment] 2015-01-07 10:17
Some information about this:

> Cert store on the mac as things changed after 10.7. So Go doesn't verify cert with the system cert store. [discussions](https://groups.google.com/forum/#!topic/golang-nuts/v5ShM8R7Tdc)

How about turn off cert verification?

**Comment by noomz** [comment] 2015-01-16 09:07
`-allow-insecure` option does not help.

**Comment by denji** [comment] 2015-02-10 16:40
+1

**Comment by ottob** [comment] 2015-02-11 14:34
`-allow-insecure` works for me, running 372ea3b0e6

**Comment by noomz** [comment] 2015-02-13 02:01
Confirm `-allow-insecure` works. Should we close this issues?

**Comment by denji** [comment] 2015-02-13 10:51
The problem with certificates is not yet solved, you need to read bundle -> `NSS Root certs ` before checking on insecurity

- https://github.com/agl/extract-nss-root-certs

**Comment by rdalverny** [comment] 2015-03-06 17:16
Looks like this is related to #29.

**Comment by wayneashleyberry** [comment] 2015-05-22 12:01
+1, I'm also getting this

```
~
❯ boom -n 1000 -c 100 https://google.com -allow-insecure
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Error distribution:
  [1000]	Get https://216.58.223.14: x509: cannot validate certificate for 216.58.223.14 because it doesn't contain any IP SANs
```

**Comment by rakyll** [comment] 2015-05-25 17:16
This is a duplicate of https://github.com/rakyll/boom/issues/29.

**Closed by rakyll** 2015-05-25 17:16 UTC
